# Generated by Django 3.2.13 on 2022-06-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=100, primary_key=True, serialize=False)),
                ('myprofile', models.ImageField(blank=True, default='img.png', null=True, upload_to='images')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
