# Generated by Django 3.2.13 on 2022-06-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghiyaszafar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
