# Generated by Django 3.2.13 on 2022-06-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghiyaszafar', '0002_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='images')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='myprofile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
