# Generated by Django 3.2.13 on 2022-06-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghiyaszafar', '0003_auto_20220605_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile',
            field=models.ImageField(blank=True, default='img.png', null=True, upload_to='images'),
        ),
    ]
