# Generated by Django 3.2.13 on 2022-06-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghiyaszafar', '0004_alter_studentprofile_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('AID', models.IntegerField(primary_key=True, serialize=False)),
                ('Bank_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='basic',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.DeleteModel(
            name='studentprofile',
        ),
    ]
